menu/urls.py
from django.conf.urls import patterns, url
from mezzanine.core.views import direct_to_template

urlpatterns = patterns('',
	# url("^$", direct_to_template, {"template": "pages/menu.html"}, name="menu"),
    url(r'^partials/menu/(\d{1,4})/$', 'bmd_cms.menu.views.menu_item_modal'),
    url(r'^partials/special/(\d{1,4})/$', 'bmd_cms.menu.views.special_modal'),
)

urls.py
from django.conf.urls.defaults import patterns, include, url
from django.contrib import admin
from django.views.generic import TemplateView
from mezzanine.core.views import direct_to_template


admin.autodiscover()

# Add the urlpatterns for any custom Django applications here.
# You can also change the ``home`` view to add your own functionality
# to the project's homepage.

urlpatterns = patterns("",

    # Change the admin prefix here to use an alternate URL for the
    # admin interface, which would be marginally more secure.
    ("^admin/", include(admin.site.urls)),

    # We don't want to presume how your homepage works, so here are a
    # few patterns you can use to set it up.

    # HOMEPAGE AS STATIC TEMPLATE
    # ---------------------------
    # This pattern simply loads the index.html template. It isn't
    # commented out like the others, so it's the default. You only need
    # one homepage pattern, so if you use a different one, comment this
    # one out.

    # url("^$", direct_to_template, {"template": "index.html"}, name="home"),

    # HOMEPAGE AS AN EDITABLE PAGE IN THE PAGE TREE
    # ---------------------------------------------
    # This pattern gives us a normal ``Page`` object, so that your
    # homepage can be managed via the page tree in the admin. If you
    # use this pattern, you'll need to create a page in the page tree,
    # and specify its URL (in the Meta Data section) as "/", which
    # is the value used below in the ``{"slug": "/"}`` part. Make
    # sure to uncheck all templates for the "show in menus" field
    # when you create the page, since the link to the homepage is
    # always hard-coded into all the page menus that display navigation
    # on the site. Also note that the normal rule of adding a custom
    # template per page with the template name using the page's slug
    # doesn't apply here, since we can't have a template called
    # "/.html" - so for this case, the template "pages/index.html" can
    # be used.

    url("^$", "mezzanine.pages.views.page", {"slug": "/"}, name="home"),

    # HOMEPAGE FOR A BLOG-ONLY SITE
    # -----------------------------
    # This pattern points the homepage to the blog post listing page,
    # and is useful for sites that are primarily blogs. If you use this
    # pattern, you'll also need to set BLOG_SLUG = "" in your
    # ``settings.py`` module, and delete the blog page object from the
    # page tree in the admin if it was installed.

    # url("^$", "mezzanine.blog.views.blog_post_list", name="home"),

    # webmaster verification tools
    url(r'', include('webmaster_verification.urls')),
    ("^menu/", include("bmd_cms.menu.urls")),

    (r'^robots\.txt$', TemplateView.as_view(template_name='robots.txt', content_type='text/plain')),

    # MEZZANINE'S URLS
    # ----------------
    # ADD YOUR OWN URLPATTERNS *ABOVE* THE LINE BELOW.
    # ``mezzanine.urls`` INCLUDES A *CATCH ALL* PATTERN
    # FOR PAGES, SO URLPATTERNS ADDED BELOW ``mezzanine.urls``
    # WILL NEVER BE MATCHED!

    # If you'd like more granular control over the patterns in
    # ``mezzanine.urls``, go right ahead and take the parts you want
    # from it, and use them directly below instead of using
    # ``mezzanine.urls``.
    ("^", include("mezzanine.urls")),

    # MOUNTING MEZZANINE UNDER A PREFIX
    # ---------------------------------
    # You can also mount all of Mezzanine's urlpatterns under a
    # URL prefix if desired. When doing this, you need to define the
    # ``SITE_PREFIX`` setting, which will contain the prefix. Eg:
    # SITE_PREFIX = "my/site/prefix"
    # For convenience, and to avoid repeating the prefix, use the
    # commented out pattern below (commenting out the one above of course)
    # which will make use of the ``SITE_PREFIX`` setting. Make sure to
    # add the import ``from django.conf import settings`` to the top
    # of this file as well.
    # Note that for any of the various homepage patterns above, you'll
    # need to use the ``SITE_PREFIX`` setting as well.

    # ("^%s/" % settings.SITE_PREFIX, include("mezzanine.urls"))

)

# Adds ``STATIC_URL`` to the context of error pages, so that error
# pages can use JS, CSS and images.
handler404 = "mezzanine.core.views.page_not_found"
handler500 = "mezzanine.core.views.server_error"

menu/models.py
from django.db import models
from mezzanine.pages.models import Page
from mezzanine.core.models import MetaData, Displayable, Orderable, RichText
from mezzanine.core.fields import RichTextField
from datetime import datetime
from django.conf import settings


class Menu(Page, RichText):
	"""This fake model is necessary to create a Mezzanine type, 
		even if it doesn't really do anything"""
	pass


class MenuItemCategory(models.Model):
	name = models.CharField(max_length=100)
	order = models.IntegerField(default=0, 
		help_text="Any positive or negative integer. Specials will always be shown first.")

	class Meta:
		verbose_name_plural = "Menu Item Categories"
		ordering = ['order', 'name']

	def __unicode__(self):
		return self.name


class MenuItem(Displayable, RichText):
	category = models.ForeignKey(MenuItemCategory)
	signature_item = models.BooleanField(help_text="Is this a BMD Signature Item?", default=False)
	category_feature = models.BooleanField(help_text="Should this be the featured item in it's category?", default=False)
	image = models.ImageField(blank=True, 
		null=True, 
		upload_to='images/menu')
	order = models.IntegerField(max_length=5,
		default=0,
		help_text="Any positive or negative integer")

	class Meta:
		ordering = ['category', '-signature_item', 'order', 'title']

	def __unicode__(self):
		return "%s [%s]" % (self.title, self.category.name)

	def get_absolute_url(self):
		return "/menuitem/%s" % self.id

	@property
	def get_image(self):
		if self.image:
			return "%s%s" % (settings.MEDIA_URL, self.image)
		else:
			return "/static/common/images/no-image.png"

	@property
	def image_absolute_url(self):
		return "%s%s" % (settings.MEDIA_URL, self.image)


class MenuItemPrice(models.Model):
	desc = models.CharField(max_length=100,
		blank=True)
	item = models.ForeignKey(MenuItem)
	price = models.FloatField(blank=True, 
		null=True)
	unit = models.CharField(max_length=10, 
		blank=True, 
		default="ea.")
	order = models.IntegerField(max_length=5,
		default=0,
		help_text="Any positive or negative integer. Leave blank to sort by ascending price (this is probably what you want anyway)")

	class Meta:
		verbose_name_plural = "Menu Item Prices"
		ordering = ['order', 'price']

	def __unicode__(self):
		return "%s %s" % (self.price, self.unit)


class Special(Displayable, RichText):
	item = models.ForeignKey(MenuItem)
	image = models.ImageField(blank=True, 
		null=True, 
		upload_to='images/specials',
		help_text="The item image will be used if this is left blank")
	price = models.FloatField(blank=True, 
		null=True,
		help_text="Use only for item-specific specials")
	unit = models.CharField(max_length=10, 
		blank=True, 
		default="ea.")
	order = models.IntegerField(max_length=5,
		default=0,
		help_text="Any positive or negative integer")

	class Meta:
		ordering = ['order', 'title']

	def __unicode__(self):
		return self.title

	def get_absolute_url(self):
		return "/special/%s" % self.id

	@property
	def get_image(self):
		return self.image or self.item.image

menu/views.py
from django.shortcuts import render_to_response
from .models import MenuItem, Special

def menu_item_modal(request, item_id):
	item = MenuItem.objects.get(pk=item_id)
	return render_to_response('partials/menuitem_modal.html', {"item": item, "imgsize": "600x400"})

def special_modal(request, item_id):
	item = Special.objects.get(pk=item_id)
	return render_to_response('partials/menuitem_modal.html', {"item": item, "imgsize": "600x400"})

menu/templates/partials/menuitem-list.html
{% load mezzanine_tags thumbnail %}
<!-- menuitem-list -->

{% if item.image %}
<a class="pull-left" href="#" data-remote="/menu/partials/{{ item.pk }}/" role="button" data-toggle="modal" data-target="#item{{ item.pk }}">
	<img src="{% thumbnail item.image imgsize crop %}" alt="image of {{ item.name }}" class="media-object" title="{{ item.name }}">
</a>
{% else %}
<a class="pull-left" href="#" data-remote="/menu/partials/{{ item.pk }}/" role="button" data-toggle="modal" data-target="#item{{ item.pk }}">
	<img src="/static/common/images/no-image.png">
</a>
{% endif %}

<div class="media-body">
    <h4 class="media-heading">
		{% if item.special %}<i class="icon-star-empty"></i>{% endif %}{{ item.name }}
    </h4>
    {% if shorttext %}
		{{ item.description|safe|truncatewords:10 }}
	{% else %}
		{{ item.description|safe }}
	{% endif %}
	{% if item.prices.all %}
		{% include "partials/menuitem-prices.html" with prices=item.menuitemprice_set.all %}
	{% endif %}
</div>
<!-- /menuitem-list -->

menu/templates/partials/menuitem-prices.html
{% for price in prices %}
	{% if price.price %}
	<p>
		{% if price.desc %}{{ price.desc }}&nbsp;{% endif %}
		<strong>${{ price.price|floatformat:2 }}</strong>
		{% if price.unit %} / {{ price.unit }}{% endif %}
	</p>
	{% endif %}
{% endfor %}

menu/templates/partials/menuitem.html
{% load mezzanine_tags thumbnail %}
<!-- menuitem -->

{% if item.image %}

{# <img src="{{ item.get_image }}" alt="image of {{ item.name }}" title="{{ item.name }}"> #}
<img src="{% thumbnail item.image imgsize crop %}" alt="image of {{ item.name }}" title="{{ item.name }}">
{% else %}
<img src="/static/common/images/no-image.png" alt="no image available" title="no image available">
{% endif %}
<div class="item">
<h4 class="title{% if item.signature_item %} signature{% endif %}">{% if special %}<i class="icon-star-empty"></i>&nbsp;{% endif %}{{ item.title }}</h4>
<div>
	<p>
	{{ item.description|safe|truncatewords:bmd_menu_item_truncate }}
	</p>
	{% if item.menuitemprice_set.all %}
		{% include "partials/menuitem-prices.html" with prices=item.menuitemprice_set.all %}
	{% endif %}
	<button data-remote="/menu/partials/{% if special %}special{% else %}menu{% endif %}/{{ item.pk }}/" role="button" class="btn btn-default btn-small" data-toggle="modal" data-target="#item{{ item.pk }}">more</button>
</div>
</div>

<!-- Modal -->
<div class="modal fade" id="item{{ item.pk }}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
</div><!-- /.modal -->
<!-- /menuitem -->

menu/templates/partials/menuitem_modal.html
{% load mezzanine_tags thumbnail %}
<div class="modal-dialog">
	<div class="modal-content color-4">
	  <div class="modal-header">
	    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
	    <h4 class="modal-title" id="myModalLabel">{{ item.title }}</h4>
	  </div>
	  <div class="modal-body">
	    {% if item.image %}
		<img src="{% thumbnail item.image imgsize crop %}" alt="image of {{ item.name }}" title="{{ item.name }}">
		{% else %}
		<img src="/static/common/images/no-image.png" alt="no image available" title="no image available">
		{% endif %}

		<h4>{% if special %}<i class="icon-star-empty"></i>{% endif %}{{ item.title }}</h4>
		<div>
			{{ item.description|safe }}
		</div>
		{% if item.price %}
		<p><strong>${{ item.price|floatformat:2 }}</strong> / {{ item.unit }}</p>
		{% endif %}
	  </div>
	  <div class="modal-footer">
	    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
	  </div>
	</div><!-- /.modal-content -->
</div><!-- /.modal-dialog -->

menu/templates/partials/menulist (copy).html
{% regroup items by category.name as cat_item_list %}
{% for item_list in cat_item_list %}

	{% if cat %}
	<h3>{{ item_list.grouper }}</h3>
	{% endif %}

	<ul class="thumbnails">
		{% for item in item_list.list %}
			<li class="span2">
				<div class="thumbnail">
					{% include "partials/menuitem.html" with imgsize="270x200" shorttext=True %}
				</div>
			</li>
			<!-- Modal -->
			<div id="item{{ item.pk }}" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
					<h3 id="myModalLabel">{{ item.name }}</h3>
				</div>
				<div class="modal-body">
					<!-- load body via ajax -->
				</div>
				<div class="modal-footer">
					<button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
				</div>
			</div>
		{% endfor %}
	</ul>
{% endfor %}

menu/templates/partials/menulist.html
<div id="menu" class="page color-4">
    <div class="inner-page">
    <div class="row">
      <div class="col-sm-6">
        <p class="signature"><small>Bake My Day Signature Item</small></p>
      </div>
      {% if download_items %}
      <div class="col-sm-6">
        <div class="download_links">
          {% for item in download_items %}
            <a class="btn btn-info" 
              href="{{ item.url }}"
              target="_blank"
              >
              {% if item.icon_class %}
              <span class="{{ item.icon_class }}"></span>
              {% endif %}{{ item.title }}
            </a>
          {% endfor %}
        </div>
      </div>
      {% endif %}
    </div>
  </div>
</div>
{% for categorized_item in items %}
  {% cycle 'color-1' 'color-4' as page_color silent %}
  {% if categorized_item.items %}
  <div id="{{ categorized_item.cat.id }}" class="page {{ page_color }}">
      <div class="inner-page">
        <div class="menu clearfix">
        {% if categorized_item.cat %}
        <h3>{{ categorized_item.cat.name }}</h3>
        {% endif %}
        <div class="row">
        {% for item in categorized_item.items %}
          {% if forloop.counter0|divisibleby:"4" %}
          <div class="row">
          {% endif %}
          <div class="col-sm-3">
            <div class="thumbnail color-4">
              {% include "partials/menuitem.html" with imgsize="320x240" shorttext=True %}
            </div>
          </div>
          {% if forloop.last or forloop.counter|divisibleby:"4" %}
          </div>
          {% endif %}
        {% endfor %}
        </div>
      </div>
    </div>
  </div>
  {% endif %}
{% endfor %}